// @ts-nocheck -- skip type checking
import * as docs_10 from "../blog/content/vibe-coding-ia-desenvolvimento.mdx?collection=docs&hash=1764518371490"
import * as docs_9 from "../blog/content/viagens-seguranca-digital.mdx?collection=docs&hash=1764518371490"
import * as docs_8 from "../blog/content/vazamento-informacoes-dlp.mdx?collection=docs&hash=1764518371490"
import * as docs_7 from "../blog/content/tscm-contramedidas-tecnicas.mdx?collection=docs&hash=1764518371490"
import * as docs_6 from "../blog/content/secops-operacoes-seguranca.mdx?collection=docs&hash=1764518371490"
import * as docs_5 from "../blog/content/ransomware-as-a-service.mdx?collection=docs&hash=1764518371490"
import * as docs_4 from "../blog/content/ot-security-ambientes-industriais.mdx?collection=docs&hash=1764518371490"
import * as docs_3 from "../blog/content/ia-generativa-seguranca.mdx?collection=docs&hash=1764518371490"
import * as docs_2 from "../blog/content/contraespionagem-digital.mdx?collection=docs&hash=1764518371490"
import * as docs_1 from "../blog/content/ciberseguranca-fundamentos.mdx?collection=docs&hash=1764518371490"
import * as docs_0 from "../blog/content/automacao-residencial-segura.mdx?collection=docs&hash=1764518371490"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"automacao-residencial-segura.mdx","absolutePath":"/home/user/esper-site/blog/content/automacao-residencial-segura.mdx"}, data: docs_0 }, { info: {"path":"ciberseguranca-fundamentos.mdx","absolutePath":"/home/user/esper-site/blog/content/ciberseguranca-fundamentos.mdx"}, data: docs_1 }, { info: {"path":"contraespionagem-digital.mdx","absolutePath":"/home/user/esper-site/blog/content/contraespionagem-digital.mdx"}, data: docs_2 }, { info: {"path":"ia-generativa-seguranca.mdx","absolutePath":"/home/user/esper-site/blog/content/ia-generativa-seguranca.mdx"}, data: docs_3 }, { info: {"path":"ot-security-ambientes-industriais.mdx","absolutePath":"/home/user/esper-site/blog/content/ot-security-ambientes-industriais.mdx"}, data: docs_4 }, { info: {"path":"ransomware-as-a-service.mdx","absolutePath":"/home/user/esper-site/blog/content/ransomware-as-a-service.mdx"}, data: docs_5 }, { info: {"path":"secops-operacoes-seguranca.mdx","absolutePath":"/home/user/esper-site/blog/content/secops-operacoes-seguranca.mdx"}, data: docs_6 }, { info: {"path":"tscm-contramedidas-tecnicas.mdx","absolutePath":"/home/user/esper-site/blog/content/tscm-contramedidas-tecnicas.mdx"}, data: docs_7 }, { info: {"path":"vazamento-informacoes-dlp.mdx","absolutePath":"/home/user/esper-site/blog/content/vazamento-informacoes-dlp.mdx"}, data: docs_8 }, { info: {"path":"viagens-seguranca-digital.mdx","absolutePath":"/home/user/esper-site/blog/content/viagens-seguranca-digital.mdx"}, data: docs_9 }, { info: {"path":"vibe-coding-ia-desenvolvimento.mdx","absolutePath":"/home/user/esper-site/blog/content/vibe-coding-ia-desenvolvimento.mdx"}, data: docs_10 }]);
export const meta = _runtime.meta<typeof _source.meta>([]);