#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Cutover de ricardoesper.com.br: Vercel → Cloudflare Workers.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

ZONE_BR="7073a176bcb22f5dd7da8bdc64ce6c79"     # ricardoesper.com.br
ZONE_COM="a1a6d1b15ecd94514576e72b33e57588"    # ricardoesper.com
ACCOUNT="0a6c490dd5fe9051422c15c9e133138e"     # NESS
CANON="www.ricardoesper.com.br"
STAGING="cf.ricardoesper.com.br"

cf() {  # cf METHOD PATH [BODY]
  local method="$1" path="$2" body="${3:-}"
  if [[ -n "$body" ]]; then
    curl -sS -X "$method" "https://api.cloudflare.com/client/v4${path}" \
      -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
      -H "Content-Type: application/json" -d "$body"
  else
    curl -sS -X "$method" "https://api.cloudflare.com/client/v4${path}" \
      -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}"
  fi
}

banner "Cutover para Cloudflare Workers"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pré-voo"
say "Antes de tocar em qualquer coisa, confiro o que precisa estar de pé."
if [[ -z "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  warn "CLOUDFLARE_API_TOKEN não está no ambiente. Sem ele, nada aqui funciona."
  exit 1
fi
command -v npx >/dev/null || { warn "npx não encontrado."; exit 1; }
step "Token presente."
if cf GET "/zones/${ZONE_BR}" | grep -q '"success":true'; then
  step "Zona ricardoesper.com.br alcançável."
else
  warn "O token não alcança a zona. Confira as permissões antes de seguir."; exit 1
fi
S_CODE=$(curl -sS -o /dev/null -w '%{http_code}' -m 30 "https://${STAGING}/pt-BR/sobre" || echo 000)
if [[ "$S_CODE" == "200" ]]; then
  step "O Worker responde em ${STAGING} — é o que vamos promover."
else
  warn "${STAGING} devolveu ${S_CODE}. O Worker precisa estar saudável antes do cutover."
  confirm "Seguir mesmo assim?" || exit 1
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "JWT_SECRET"
say "Assina a sessão do admin. É gerado aqui — você não precisa ter o valor."
note "Efeito colateral: sessões antigas caem e você faz login de novo."
if confirm "Gerar e gravar agora?"; then
  openssl rand -base64 48 | npx wrangler secret put JWT_SECRET \
    && step "Gravado no Worker." \
    || warn "Falhou. Rode à mão: npx wrangler secret put JWT_SECRET"
else
  SKIPPED+=("JWT_SECRET — o admin não vai logar sem ele")
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Turnstile"
say "Protege /api/comments. São dois valores: a chave secreta e a pública."
warn "Sem as duas, o formulário de comentários não valida."
open_url "https://dash.cloudflare.com/${ACCOUNT}/turnstile"
step "Abra o widget do site (ou crie um para ${CANON})."
step "Copie a Site Key — é pública, vai no wrangler.toml."
ask TURNSTILE_SITE_KEY "Cole a Site Key:"
step "Copie a Secret Key."
ask_secret TURNSTILE_SECRET_KEY "Cole a Secret Key:"
if [[ -n "$TURNSTILE_SECRET_KEY" ]]; then
  printf '%s' "$TURNSTILE_SECRET_KEY" | npx wrangler secret put TURNSTILE_SECRET_KEY \
    && step "Secret gravado no Worker." \
    || warn "Falhou ao gravar o secret."
fi
if [[ -n "$TURNSTILE_SITE_KEY" ]]; then
  sed -i.bak "s|^NEXT_PUBLIC_TURNSTILE_SITE_KEY = .*|NEXT_PUBLIC_TURNSTILE_SITE_KEY = \"${TURNSTILE_SITE_KEY}\"|" wrangler.toml \
    && rm -f wrangler.toml.bak && step "Site Key escrita no wrangler.toml."
  warn "Isso mudou um arquivo versionado: precisa de commit e novo deploy."
  SKIPPED+=("commit do wrangler.toml + npm run build:cf && npx wrangler deploy")
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "esper.ws: o redirect preserva o caminho?"
say "Esta é a incógnita que decide o destino do esper.ws."
note "Se preservar, ele fica na Hostinger para sempre e o e-mail nunca é tocado."
note "Se não preservar, os links históricos caem na home — e aí é outra conversa."
open_url "https://hpanel.hostinger.com/"
step "Domínios → esper.ws → procure Redirecionamentos (ou Redirects)."
step "Crie: de  esper.ws  para  https://${STAGING}"
step "Se houver escolha entre 301 e 302, escolha 301."
note "Aponto para o hostname de teste de propósito: não derruba nada se der errado."
pause "Configurado? Enter para eu medir."
say ""
step "Medindo..."
DEST=$(curl -sSL -m 40 -o /dev/null -w '%{url_effective}' \
  "https://esper.ws/2024/01/huaqiangbei-shenzhen" 2>/dev/null || echo "")
say "  chegou em: ${DEST:-<sem resposta>}"
if [[ "$DEST" == *"huaqiangbei"* || "$DEST" == *"shenzhen"* ]]; then
  step "PRESERVA o caminho. O esper.ws pode ficar onde está."
elif [[ -n "$DEST" ]]; then
  warn "NÃO preserva — caiu na raiz. Mover a zona vira necessário."
  SKIPPED+=("esper.ws: decidir migração de zona (22 registros, e-mail Google Workspace)")
else
  warn "Sem resposta. Talvez o DNS ainda não tenha propagado; repita depois."
  SKIPPED+=("esper.ws: repetir o teste de preservação de caminho")
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "A virada"
warn "É AQUI que o visitante muda de servidor."
say ""
say "O que vai acontecer, nesta ordem:"
step "1. Apagar o CNAME de ${CANON} (hoje aponta para o apex, servido pela Vercel)."
step "2. Adicionar ${CANON} como Custom Domain do Worker esper-site."
say ""
say "ROLLBACK — anote antes de continuar:"
note "  Recriar em ricardoesper.com.br:  CNAME  www  →  ricardoesper.com.br  (sem proxy)"
note "  A Vercel continua de pé; ela só sai dias depois, e é essa a rede."
say ""
warn "Há uma janela de segundos entre apagar e recriar."
if ! confirm "Virar a chave agora?"; then
  SKIPPED+=("A virada do ${CANON} — nada foi alterado")
  finish; exit 0
fi
REC=$(cf GET "/zones/${ZONE_BR}/dns_records?name=${CANON}" \
  | grep -oE '"id":"[a-f0-9]{32}"' | head -1 | cut -d'"' -f4)
if [[ -n "$REC" ]]; then
  cf DELETE "/zones/${ZONE_BR}/dns_records/${REC}" >/dev/null && step "CNAME antigo removido."
else
  note "Nenhum CNAME encontrado — talvez já tenha sido removido."
fi
RESP=$(cf PUT "/accounts/${ACCOUNT}/workers/domains" \
  "{\"environment\":\"production\",\"hostname\":\"${CANON}\",\"service\":\"esper-site\",\"zone_id\":\"${ZONE_BR}\"}")
if grep -q '"success":true' <<<"$RESP"; then
  step "${CANON} agora é Custom Domain do Worker."
else
  warn "Falhou ao ligar o domínio. Resposta:"
  say "$RESP"
  warn "ROLLBACK: recrie o CNAME www → ricardoesper.com.br, sem proxy."
  exit 1
fi
pause "Aguarde o certificado (costuma levar segundos). Enter para verificar."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verificação"
say "Conferindo o domínio real, não o de teste."
for _ in $(seq 1 30); do
  [[ "$(curl -sS -o /dev/null -w '%{http_code}' -m 20 "https://${CANON}/robots.txt" || echo 000)" == "200" ]] && break
  sleep 10
done
H=$(curl -sSL -m 40 "https://${CANON}/pt-BR/sobre" || echo "")
P=$(curl -sSL -m 40 "https://${CANON}/pt-BR/blog" | grep -o "href=\"/pt-BR/blog/[a-z0-9-]*\"" | sort -u | wc -l)
SM=$(curl -sSL -m 40 "https://${CANON}/sitemap.xml" | grep -c "<loc>" || echo 0)
HT=$(grep -c "<html" <<<"$H" || echo 0)
say ""
printf '  posts no blog      %s   %s\n' "$P"  "$([[ $P  -ge 25 ]] && echo ✓ || echo '← esperado ~29')"
printf '  URLs no sitemap    %s   %s\n' "$SM" "$([[ $SM -ge 40 ]] && echo ✓ || echo '← esperado 47')"
printf '  <html> na página   %s   %s\n' "$HT" "$([[ $HT -eq 1 ]] && echo ✓ || echo '← esperado 1')"
say ""
if [[ $P -ge 25 && $SM -ge 40 && $HT -eq 1 ]]; then
  step "O Worker está servindo o domínio, com o conteúdo do D1."
else
  warn "Algo não bate. O rollback continua sendo recriar o CNAME www."
  confirm "Seguir para os 301 mesmo assim?" || { finish; exit 1; }
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Os 301 e o Search Console"
say "Os outros hostnames passam a redirecionar para o canônico, preservando o caminho."
if confirm "Criar as Redirect Rules agora?"; then
  for Z in "$ZONE_BR" "$ZONE_COM"; do
    # PUT no entrypoint da fase cria ou substitui o ruleset inteiro. É
    # idempotente — rodar de novo não duplica regra — e dispensa descobrir
    # o id de um ruleset que pode nem existir.
    RESP=$(cf PUT "/zones/${Z}/rulesets/phases/http_request_dynamic_redirect/entrypoint" "$(cat <<JSON
{"rules":[{
  "action":"redirect",
  "expression":"(http.host ne \"${CANON}\")",
  "description":"Tudo que nao e o canonico vai para ele, preservando o caminho",
  "action_parameters":{"from_value":{
    "status_code":301,
    "target_url":{"expression":"concat(\"https://${CANON}\", http.request.uri.path)"},
    "preserve_query_string":true
  }}
}]}
JSON
)")
    if grep -q '"success":true' <<<"$RESP"; then
      step "Regra 301 ativa na zona ${Z}."
    else
      warn "Falhou na zona ${Z}:"
      say "$(head -c 300 <<<"$RESP")"
      SKIPPED+=("Redirect Rule da zona ${Z}")
    fi
  done
else
  SKIPPED+=("Redirect Rules dos hostnames secundários")
fi
say ""
say "Agora o Search Console — só você tem acesso."
open_url "https://search.google.com/search-console"
step "Submeta https://${CANON}/sitemap.xml"
step "Em esper.ws, use Mudança de Endereço apontando para ${CANON}."
step "Exporte o relatório de 404 — é a lista que falta para completar o mapa de redirects."
SKIPPED+=("Vercel: desativar a integração DIAS depois, não hoje — ela é o rollback")
pause

finish
